kind: imagerunner
apiVersion: v1alpha

suites:
  - name: "WebdriverIO in ImageRunner"
    workload: webdriver
    image: saucelabs/imagerunner-webdriverio-example:latest
    timeout: 10m
    artifacts:
      - "/app/artifacts/screenshots"

artifacts:
  cleanup: false
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts
