kind: imagerunner
apiVersion: v1alpha

defaults:
  workload: other

suites:
  - name: "Playwright in ImageRunner"
    image: fpsl/dummy-runner:playwright-1.32.0
    timeout: 10m
    artifacts:
      - "/app/artifacts/test-results"
    env:
      SAUCE_USERNAME: $SAUCE_USERNAME
      SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY

artifacts:
  cleanup: false
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts
