apiVersion: v1alpha
kind: imagerunner

sauce:
  region: ${SAUCE_REGION}

suites:
  - name: java-junit-selenium
    image: saucelabs/imagerunner-java-junit-selenium:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: mvn -pl best-practice test -Dtest=DesktopTests
