apiVersion: v1alpha
kind: imagerunner

sauce:
  region: ${SAUCE_REGION}

suites:
  - name: photon-java
    image: saucelabs/imagerunner-java-junit-appium:latest
    resourceProfile: c3m3
    workload: webdriver
