apiVersion: v1alpha
kind: imagerunner

sauce:
  region: ${SAUCE_REGION}

suites:
  - name: java-junit-selenium
    image: saucelabs/imagerunner-java-junit-selenium:latest
    resourceProfile: c3m3
    workload: webdriver
    entrypoint: mvn -pl best-practice test -Dtest=DesktopTests
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_REGION: ${SAUCE_REGION}
      SAUCE_BUILD_TYPE: Orchestrate
