kind: imagerunner
apiVersion: v1alpha

suites:
  - name: "WebdriverIO in ImageRunner"
    workload: other
    ## FIXME: Use saucelabs registry
    image: fpsl/wdio-hto-runner:latest
    timeout: 10m
    env:
      SAUCE_USERNAME: $SAUCE_USERNAME
      SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY

artifacts:
  cleanup: false
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts
