name: java-testng-selenium example

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: java-testng-selenium
          push: true
          load: false
          tags: saucelabs/imagerunner-java-testng-selenium:latest
          platforms: linux/amd64,linux/arm64

  run-java-testng-selenium-on-sauce:
    runs-on: ubuntu-latest
    needs:
      - build-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: saucelabs/saucectl-run-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          working-directory: "./java-testng-selenium/"
          region: us-west-1
