name: saucectl imagerunner example

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  NODE_VERSION: 18

jobs:
  ## FIXME: Build + Publish image upfront
  test-playwright:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup saucectl
        uses: saucelabs/saucectl-run-action@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          working-directory: "./playwright/"
          env: |
            SAUCE_USERNAME=$SAUCE_USERNAME
            SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
