name: WebdriverIO ImageRunner Example

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  NODE_VERSION: 20

jobs:
  run-wdio-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install
        working-directory: ./webdriverio/

      - name: Run
        run: npm run test.local
        working-directory: ./webdriverio/

  build-wdio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: webdriverio
          push: true
          load: false
          tags: saucelabs/imagerunner-webdriverio-example:latest

  run-wdio-sauce:
    runs-on: ubuntu-latest
    needs: [build-wdio]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: saucelabs/saucectl-run-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          working-directory: "./webdriverio/"
          region: us-west-1
          env: |
            SAUCE_USERNAME=$SAUCE_USERNAME
            SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
